services:
  - type: web
    name: ai-stock-dashboard
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You'll manually add this in the Render dashboard

