services:
  - type: web
    name: ai-stock-dashboard
    env: python          # ← keep this exactly “python”
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

    envVars:
      - key: OPENAI_API_KEY
        sync: false       # set the real value in Render’s dashboard
